apiVersion: v1
kind: Service
metadata:
    name: business-logic-service
spec:
    selector:
        app: business-logic
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
