apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-admin-binding
subjects:
  - kind: ServiceAccount
    name: portainer-dev-sa
    namespace: portainer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
