apiVersion: v1
kind: Service
metadata:
    name: web-app-service
spec:
    type: NodePort
    selector:
        app: web-app
    ports:
        - protocol: TCP
          port: 5173
          targetPort: 5173
          nodePort: 30003
