apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-claim
  labels:
    app: postgres-db
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi